Langs:
- C#
- Java
- Javascript
- PHP
- Python
- C++
- .NET
- HTML/CSS
- HTML
- CSS
- Objective-C
- C
- Ruby
- Perl
- Delphi
- Scala
- Haskell
- Lisp

DataFile: /Users/Renfred/Desktop/Data/stackoverflow.com-Posts
